### ISSUE TITLE
[Bug]: Images did not appear in fullscreen as in documentation

### ISSUE THREAD

**Issue by oggiesutrisna** [diogogpinto/filament-auth-ui-enhancer#7] opened 2024-10-23 02:32 UTC
### What happened?

![image](https://github.com/user-attachments/assets/63c468a6-c500-4973-a459-2a7ce80310ea)
I just followed the documentation but it appears like this. am I breaking something or am I doing it wrong. 

### How to reproduce the bug

When I delete
`->formPanelPosition('left')` changes to right, it appears on bottom. 

### Package Version

1.0.0

### PHP Version

8.3

### Laravel Version

11.29

### Which operating systems does with happen with?

Windows

**Comment by diogogpinto** [comment] 2024-10-23 10:33
Hello @oggiesutrisna 

This is a problem with your theme configuration and build process.

I will try to release a more in depth guide later today.

Thank you!

**Comment by oggiesutrisna** [comment] 2024-10-23 13:47
Ohh, okayy, thanks for replying, 

I just followed the instructions on your documentations, installing custom theme using bun and seems fine for me, checking for the 2nd time and it don't make issues. 

Can't wait for the depth guide.

**Comment by diogogpinto** [comment] 2024-10-31 11:31
Hello @oggiesutrisna 

Here's my "full guide". You can take a look and let me know what you think:

https://github.com/diogogpinto/filament-themes-full-guide

I'll close this for now as it looks like the problem is solved. :)

**Closed by diogogpinto** 2024-10-31 11:31 UTC
Labels: bug
